name: istc_bouakeapp
description: "Application mobile de l'ISTC Polytechnique Bouaké"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Black.ttf
        - asset: assets/fonts/DMSans_18pt-BlackItalic.ttf
        - asset: assets/fonts/DMSans_18pt-SemiBold.ttf
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
        - asset: assets/fonts/DMSans_18pt-BoldItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Italic.ttf
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-ExtraLightItalic.ttf
        - asset: assets/fonts/DMSans_18pt-ExtraLight.ttf
        - asset: assets/fonts/DMSans_18pt-Light.ttf
        - asset: assets/fonts/DMSans_18pt-LightItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
        - asset: assets/fonts/DMSans_18pt-MediumItalic.ttf
        - asset: assets/fonts/DMSans_18pt-Regular.ttf
        - asset: assets/fonts/DMSans_18pt-SemiBold.ttf
        - asset: assets/fonts/DMSans_18pt-SemiBoldItalic.ttf